apiVersion: v1
kind: Pod
metadata:
  name: enviroments
spec:
  containers:
    - name: c00
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Vishnu Reddy; sleep 1; done"]
      env:
        - name: VISHNU_M_1
          value: vishnu1

    - name: c01
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Vishnu Reddy; sleep 1; done"]
      env:
        - name: VISHNU_M_2
          value: vi
