apiVersion: v1
kind: Pod
metadata:
  name: multi-pod-env
spec:
  containers:
    - name: con1
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Vishnu Reddy; sleep 1; done"]
      env:
        - name: VISHNU_M_1
          value: vishnu1

    - name: con2
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Vishnu Reddy; sleep 1; done"]
      env:
        - name: VISHNU_M_2
          value: vishnu2exit
